# Generated by Django 5.0.1 on 2024-02-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='userid',
        ),
    ]
