# Generated by Django 5.0.1 on 2024-02-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_user_id_todo_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='userid',
            new_name='user_id',
        ),
    ]
