# Generated by Django 5.0.2 on 2024-04-03 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_userid_todo_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user_id',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('taskDate', models.DateField(default=django.utils.timezone.now)),
                ('taskName', models.CharField(max_length=300)),
                ('taskDescription', models.TextField(max_length=1000)),
                ('taskStatus', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
